### PR TITLE
Add boot_id, energy_since_boot and time_since_boot (fixes #48)

### LINKED ISSUE #48: Please add energy_since_boot
It'd be great if you could add support for the `energy_since_boot` parameter from https://api.mystrom.ch/#fbb2c698-e37a-4584-9324-3f8b2f615fe2:

### Request
```
curl --location -g 'http://[switch_ip]/report'
```

### Response
```json
{
  "power": 240.67,
  "Ws": 226.89,
  "relay": true,
  "temperature": 25.72,
  "boot_id": "A425D9AD",
  "energy_since_boot": 299535913.95,
  "time_since_boot": 2234232
}
```

### PR DESCRIPTION
**Pull request by slyoldfox**

### CODE REVIEW

**Comment by dbrgn** [comment]
@fabaff sorry to bother you (I know how it is to be on the maintainer side of things), but any chance that you could take a look at this (and also #49) in the near future?

If you need assistance / collaborators for the maintenance, I'd be willing to help out occasionally with the review of PRs.

**Review by dbrgn — APPROVED** [review]
I haven't tested this in practice, but the code looks good to me.

Note: Older switches do not expose these fields.

On an old switch with firmware 2.68.10, the report endpoint returns:

```json
{
	"power":	0,
	"relay":	true
}
```

On a new switch v2 with firmware 4.0.14, the report endpoint returns:

```json
{"power":0.81,"Ws":0.77,"relay":true,"temperature":2.93,"boot_id":"389A7653","energy_since_boot":31719494.64,"time_since_boot":1586856}
```

However, this should be covered by the `KeyError` handling in the code, the fields will simply not be available.

**Review by fabaff — APPROVED** [review]
Thanks

**Comment by dbrgn** [comment]
Thanks @fabaff, and frohe Festtage 🙂

**Comment by dbrgn** [comment]
@fabaff thanks for merging this MR and fixing CI. Any chance for pushing a release to PyPI? Then we could update the HomeAssistant integration.

**Pull request merged**
